//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcTraining4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int CUSTOMER_ID { get; set; }
        [Display(Name = "Name:")]
        [Required(ErrorMessage = "Name cannot be blank.")]
        public string CUSTOMER_NAME { get; set; }
        [DataType(DataType.Password)]   
        [Required(ErrorMessage = "Password cannot be blank!")]
        [Display(Name = "Password:")]
        [RegularExpression(@"^(?=.*\d).{4,8}$",ErrorMessage = "Password must be between 4 and 8 digits long and include at least one numeric digit.")]
        public string CUSTOMER_PASSWORD { get; set; }
        [Display(Name = "Confirm Password:")]
        [DataType(DataType.Password)]
        [Compare("CUSTOMER_PASSWORD",ErrorMessage = " Passwords do not match.")]
        public string confirmPassword { get; set; }
        [Required(ErrorMessage = "Email Address cannot be blank.")]
        [Display(Name = "Email:")]   
        [RegularExpression(@"^[\w-\.]+@([\w -]+\.)+[\w-]{2,4}$", ErrorMessage = "Wrong email address!Please try again.")]
        public string CUSTOMER_EMAIL { get; set; }
        }
}
